### ISSUE TITLE
4.5.8 Dose response curve fitting: user specifies parameters of equation

### ISSUE THREAD

**Issue by monicaseing** [platify/platify#21]
Req. 5.8

**Comment by henstockpv** [comment]
More specifically, the user may want to fix some parameters rather than have them fit.  A trivial example would be fitting lines but requiring that they go through the origin.  You free-fit the slope but are specifying the intercept.  Similarly, dose response curves have 5 parameters typically and the users may want to specify fits for sets of them.  The idea would be to click on 5 different plots and specify the lower plateau of 0.  Click on all of them and set the hill slope = 1.0.  Doing this on a per-compound is too tedious.
