### ISSUE TITLE
4.4.4 Knock out capability selected well/plate

### ISSUE THREAD

**Issue by vinodhalaharvi** [platify/platify#32]

**Comment by reagan83** [comment]
@vinodhalaharvi can you add what req this is for in the title (see other open issues)

**Comment by vinodhalaharvi** [comment]
Reagan, this 4.4.4 from the word document. I am not sure if this is covered
else where in the issues list.

I think Monica is the expert here with the requirement mapping as she has
done majority of the work ( if I am right). From Monica's last email, I
gather that the issue list is not one for one with the requirement's and it
was deemed during the meeting that it's not worth mapping them.  I think
this would get more and more confusing as we go further in to the project.
But oh well...

-Vinod

**Comment by monicaseing** [comment]
@REMitchell adding you to this since they are pretty much doing the same thing: marking stuff as "exclude". This one is talking about selecting wells or plates to exclude when QCing, while the other issue is about selecting outliers on visualizations to remove (the values are usually normalized by this point).

**Comment by REMitchell** [comment]
Yeah, I guess this would be two different use cases ("Oh, this is an outlier, take it out" and "Oh, we don't want this for some mysterious reason, take it out") but would basically be the same feature
