### ISSUE TITLE
4.2.4 Create LH mapping file: get compound location/concentration (spoof)

### ISSUE THREAD

**Issue by monicaseing** [platify/platify#9]
Input list of compoundIDs to get location/concentration of compound

**Comment by reagan83** [comment]
I plan to wrap up our Liquid Handler integrations with this one....

**Comment by reagan83** [comment]
This is the issue we are waiting for clarification from Peter on.

**Comment by reagan83** [comment]
![lh](https://cloud.githubusercontent.com/assets/1036874/14572771/9b096f88-0305-11e6-8aa0-4798f0b9a418.png)

per @monicaseing 's suggestion

**Comment by reagan83** [comment]
(creating a Map button)

**Comment by reagan83** [comment]
Per discussion on Slack, the mapping function of the LH will work as such:

1) Scientist selects LH to contact 
 - This will be available through a "Map" button on the list page as Monica suggested (see screenshot above)

2) Scientist specifies which virtual assay to create plates for
 - This will be from a drop down list of Assay Names from Platify

3) Platify looks through the plateset for every compound needed (the compounds were specified during plate creation)
 - This will be populated by the Compound Names from the Plates in the Assays selected in item #2 above.

4) Make call to LH to generate:
 - This will allow us to fill out a LH mapping file (pending Peter's approval) for EACH Compound Name from Platify:

New Row/File:

Platify Compound Name, Liquid Handler plateId, LH well, LH dose, Platify plateId, Platify Well, Platify Dose

**Comment by reagan83** [comment]
Per Peter's notes:

Liquid Handling Workflow  4/15/2016

Starting state:

End state:

Start with the destination plates.  You have maybe 20 plates to fill and 96 compounds each.

Query the database and ask where you can find CPD-123456, CPD-1324567, CPD-32432432, etc.

System responds with a barcode, a well, and a concentration.  So your spoofed web service will respond 

with the answer to the question of where is my compound?  In the real world, this will be an inventory 

database that Platify can talk to, but which is beyond the scope of your project so you are spoofing the 

interface.   You can query through the service one compound at a time or all at once.  We’ll assume that 

the spoofed web service can handle one of these two approaches.  

You now need a human to transport those plates to the liquid handler and place them in a specified 

order.  They pull up a cart and start defrosting them from the -90C or wherever they were chilling.  The 

next step is to tell the human to load the plates into the liquid handler machine in a specific order that 

your liquid handler can manage.

The things that look like raised platforms at the bottom of the Tecan instrument are fixed positions for 

the plates—source and destination.   In many cases, they may also have a plate stacker that can handle 

lots of plates and move them in and out for both the source and destination plates.  

You might give the robot 50 plates in a specified order (that you provide) that correspond to 50 plate 

positions.  

In other cases, everything is fixed so you have to deal out 5 source plates to positions 1-5 that you 

specify and put 2 destination plates at fixed positions.

These two cases can be handled in the same way where you provide instructions for the user usually in 

the form of a comment.

# plate pos1  Barcode 234324

#plate pos2 Barcode 23523523

#plate pos3 Barcode 23523423

SrcPos1   well1  10uM   SrcPos2 wellA2 5uM

SrcPos2  well2  20uM  SrcPos2  wellA1  5uM

…

# plate pos1 Barcode 23423523   this comment is instructions for the user to do something

# plate pos2 Barcode 125231515

Let’s back up a step now.  In order for you to figure out how to create this mapping file, you need to 

know the configuration that the liquid handler can accept.  You query it to find out how many source 

and destination plates it can handle.   This is achieved through a query to the liquid handler that is 

stored in some database somewhere or perhaps the liquid handler itself.  Regardless, you can spoof a 

query to get these two values (# source and #dest plates) back any way you like.  

With the two values, you can create the liquid handler control file.  You have to specify the instructions 

to make the dest plates.  There are optimal orderings, but let’s just focus on creating the plates using a 

greedy algorithm.  That is, load up your destination plates as many as will fit.  Then load up source plates 

that will satisfy the first destination plate’s needs.  Write out the positions for these plates for the user 

as comments in the file.  Then fill up all the available destination plates with the ordered sequence of 

source plates.  That is, take source plate 1 and put wells anywhere in the destination plates for that 

setting.  Go plate by plate.  Then take source plate 2 and repeat until you’ve done all the operations.  At 

some point you will have completed and incomplete plates.   Replace the complete plates (source or 

destination) with new plates that satisfy the next requirement.  Write the comment instructions for the 

users.  

Let’s create an example:  3 wells each plate.  Plate holder holds 2 input and 2 output.

Src Plate A:  a b c

Src Plate B  d e f

Src Plate C: g h i

Dest Plate1  a h i

Dest plate 2 b h g

Dest plate 3 g h c

# Dest Plate1 = dest position 1

# Dest Plate2 = dest position 2 

To figure out the src plates, I’ll look at the first plate and realize it’s A and C

# Src Plate A = src position 1

# Src Plate C = src position 2  chosen since we need h & I from plate C

srcA  well1 a-conc   dest1 well1 a-conc

srcC  well2 h-conc  dest1 well2 h-conc

srcC well3 i-conc   dest1 well3 i-conc

srcA well2 b-conc  dest2 well1 b-conc

srcC well3 h-conc dest2 well2 h-conc

can’t do the rest of plate 2 since it needs a g and so we must be done

# Src Plate C = src position 2

# Dest Plate C = dest position 1

Keep going...

**Comment by reagan83** [comment]
The get compound location / concentration has been spoof'd from the Liquid Handler!
